# Generated by Django 4.0.6 on 2022-11-19 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ttgen', '0004_timetable'),
    ]

    operations = [
        migrations.DeleteModel(
            name='timetable',
        ),
    ]
